// import { solveDay1Part1, solveDay1Part2 } from "./day-1/index.ts";
// import { solveDay2Part1, solveDay2Part2 } from "./day-2/index.ts";
// import { solveDay3Part1, solveDay3Part2 } from "./day-3/index.ts";
// import { solveDay4Part1, solveDay4Part2 } from "./day-4/index.ts";
// import { solveDay5Part1, solveDay5Part2 } from "./day-5/index.ts";
// import { solveDay6Part1, solveDay6Part2 } from "./day-6/index.ts";
// import { solveDay7Part1, solveDay7Part2 } from "./day-7/index.ts";
// import { solveDay8Part1, solveDay8Part2 } from "./day-8/index.ts";
// import { solveDay9Part1, solveDay9Part2 } from "./day-9/index.ts";
// import { solveDay11Part1, solveDay11Part2 } from "./day-11/index.ts";
// import { solveDay12Part1, solveDay12Part2 } from "./day-12/index.ts";
// import { solveDay13Part1, solveDay13Part2 } from "./day-12/index.ts";
// import { solveDay13Part1, solveDay13Part2 } from "./day-13/index.ts";
// import { solveDay14Part1, solveDay14Part2 } from "./day-14/index.ts";
// import { solveDay15Part1, solveDay15Part2 } from "./day-15/index.ts";
// import { solveDay16Part1, solveDay16Part2 } from "./day-16/index.ts";
// import { solveDay17Part1, solveDay17Part2 } from "./day-17/index.ts";
// import { solveDay18Part1, solveDay18Part2 } from "./day-18/index.ts";
// import { solveDay19Part1, solveDay19Part2 } from "./day-19/index.ts";
// import { solveDay20Part1, solveDay20Part2 } from "./day-20/index.ts";
// import { solveDay21Part1, solveDay21Part2 } from "./day-21/index.ts";
// import { solveDay22Part1, solveDay22Part2 } from "./day-22/index.ts";
import { solveDay23Part1, solveDay23Part2 } from "./day-23/index.ts";

// console.log("Day 1, part 1:", await solveDay1Part1());
// console.log("Day 1, part 2:", await solveDay1Part2());
// console.log("Day 2, part 1:", await solveDay2Part1());
// console.log("Day 2, part 2:", await solveDay2Part2());
// console.log("Day 3, part 1:", await solveDay3Part1());
// console.log("Day 3, part 2:", await solveDay3Part2());
// console.log("Day 4, part 1:", await solveDay4Part1());
// console.log("Day 4, part 2:", await solveDay4Part2());
// console.log("Day 5, part 1:", await solveDay5Part1());
// console.log("Day 5, part 2:", await solveDay5Part2());
// console.log("Day 6, part 1:", await solveDay6Part1());
// console.log("Day 6, part 2:", await solveDay6Part2());
// console.log("Day 7, part 1:", await solveDay7Part1());
// console.log("Day 7, part 2:", await solveDay7Part2());
// console.log("Day 8, part 1:", await solveDay8Part1());
// console.log("Day 8, part 1:", await solveDay8Part2());
// console.log("Day 9, part 1:", await solveDay9Part1());
// console.log("Day 9, part 2:", await solveDay9Part2());
// console.log("Day 10, part 1:", await solveDay10Part1());
// console.log("Day 10, part 2:", await solveDay10Part2());
// console.log("Day 11, part 1:", await solveDay11Part1());
// console.log("Day 11, part 2:", await solveDay11Part2());
// console.log("Day 12, part 1:", await solveDay12Part1());
// console.log("Day 12, part 2:", await solveDay12Part2());
// console.log("Day 13, part 2:", await solveDay13Part1());
// console.log("Day 13, part 2:", await solveDay13Part2());
// console.log("Day 14, part 1:", await solveDay14Part1());
// console.log("Day 14, part 2:", await solveDay14Part2());
// console.log("Day 15, part 1:", await solveDay15Part1());
// console.log("Day 15, part 2:", await solveDay15Part2());
// console.log("Day 16, part 1:", await solveDay16Part1());
// console.log("Day 16, part 2:", await solveDay16Part2());
// console.log("Day 17, part 1:", await solveDay17Part1());
// console.log("Day 17, part 2:", await solveDay17Part2());
// console.log("Day 18, part 1:", await solveDay18Part1());
// console.log("Day 18, part 2:", await solveDay18Part2());
// console.log("Day 19, part 1:", await solveDay19Part1());
// console.log("Day 19, part 2:", await solveDay19Part2());
// console.log("Day 20, part 1:", await solveDay20Part1());
// console.log("Day 20, part 2:", await solveDay20Part2());
// console.log("Day 21, part 1:", await solveDay21Part1());
// console.log("Day 21, part 2:", await solveDay21Part2());
// console.log("Day 22, part 1:", await solveDay22Part1());
// console.log("Day 22, part 2:", await solveDay22Part2());
console.log("Day 23, part 1:", await solveDay23Part1());
console.log("Day 23, part 2:", await solveDay23Part2());
